# Generated by Django 4.1.1 on 2022-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='flat_amount',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product_discount',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
