# Generated by Django 4.1.1 on 2022-09-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_discount_flat_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='flat_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product_discount',
            field=models.FloatField(default=0),
        ),
    ]
