# Generated by Django 4.1.1 on 2022-09-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_discount_flat_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='flat_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product_discount',
            field=models.IntegerField(default=0),
        ),
    ]
