# Generated by Django 4.1.1 on 2022-09-23 17:23

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_product_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=category.models.upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
